#ifndef HTTP_PLUGIN_CALLBACKS_H
#define HTTP_PLUGIN_CALLBACKS_H

enum plugin_callback_e {
  HANDLE_REQUEST,
  HANDLE_DATA,
  INCOMING_FRAME,
  INCOMING_FRAME_DATA,
  INCOMING_FRAME_HEADERS,
  INCOMING_FRAME_PRIORITY,
  INCOMING_FRAME_RST_STREAM,
  INCOMING_FRAME_SETTINGS,
  INCOMING_FRAME_PUSH_PROMISE,
  INCOMING_FRAME_PING,
  INCOMING_FRAME_GOAWAY,
  INCOMING_FRAME_WINDOW_UPDATE,
  INCOMING_FRAME_CONTINUATION,
  POSTPROCESS_INCOMING_FRAME,
  OUTGOING_FRAME,
  OUTGOING_FRAME_DATA,
  OUTGOING_FRAME_HEADERS,
  OUTGOING_FRAME_PRIORITY,
  OUTGOING_FRAME_RST_STREAM,
  OUTGOING_FRAME_SETTINGS,
  OUTGOING_FRAME_PUSH_PROMISE,
  OUTGOING_FRAME_PING,
  OUTGOING_FRAME_GOAWAY,
  OUTGOING_FRAME_WINDOW_UPDATE,
  OUTGOING_FRAME_CONTINUATION,
  OUTGOING_FRAME_SENT,
  OUTGOING_FRAME_DATA_SENT,
  OUTGOING_FRAME_HEADERS_SENT,
  OUTGOING_FRAME_PRIORITY_SENT,
  OUTGOING_FRAME_RST_STREAM_SENT,
  OUTGOING_FRAME_SETTINGS_SENT,
  OUTGOING_FRAME_PUSH_PROMISE_SENT,
  OUTGOING_FRAME_PING_SENT,
  OUTGOING_FRAME_GOAWAY_SENT,
  OUTGOING_FRAME_WINDOW_UPDATE_SENT,
  OUTGOING_FRAME_CONTINUATION_SENT
};

struct plugin_invoker_t;

bool plugin_invoke(struct plugin_invoker_t * invoker, enum plugin_callback_e cb, ...);

#endif
