#ifndef HTTP_PLUGIN_CALLBACKS_H
#define HTTP_PLUGIN_CALLBACKS_H

enum plugin_callback_e {
  HANDLE_REQUEST,
  HANDLE_DATA,
  INCOMING_FRAME,
  INCOMING_FRAME_DATA,
  INCOMING_FRAME_HEADERS,
  INCOMING_FRAME_PRIORITY,
  INCOMING_FRAME_RST_STREAM,
  INCOMING_FRAME_SETTINGS,
  INCOMING_FRAME_PUSH_PROMISE,
  INCOMING_FRAME_PING,
  INCOMING_FRAME_GOAWAY,
  INCOMING_FRAME_WINDOW_UPDATE,
  INCOMING_FRAME_CONTINUATION,
  POSTPROCESS_INCOMING_FRAME,
};

struct plugin_invoker_t;

bool plugin_invoke(struct plugin_invoker_t * invoker, enum plugin_callback_e cb, ...);

#endif
